# Generated by Django 5.1 on 2024-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='codigo',
            field=models.CharField(default='TEMP_CODE_Ambiente', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(default='TEMP_CODE_Equipo', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='detalleambienteequipo',
            unique_together={('ambiente', 'equipo')},
        ),
    ]
